#ifndef MBEDTLS_CONFIG_8086_H
#define MBEDTLS_CONFIG_8086_H

#include <oslib.h> 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

extern void *calloc(size_t n, size_t size);

#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES


#undef MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE

#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_CALLOC_MACRO calloc
#define MBEDTLS_PLATFORM_FREE_MACRO   free
#define MBEDTLS_PLATFORM_SNPRINTF_MACRO snprintf
#define MBEDTLS_PLATFORM_PRINTF_MACRO printf


#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_PROTO_TLS1_2


#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED


#define MBEDTLS_RSA_C
#define MBEDTLS_PKCS1_V15  
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_AES_C
#define MBEDTLS_GCM_C      
#define MBEDTLS_CIPHER_MODE_CBC 


#define MBEDTLS_MD_C
#define MBEDTLS_SHA1_C     
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C   


#define MBEDTLS_ECDH_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED


#define MBEDTLS_ENTROPY_C
#define MBEDTLS_CTR_DRBG_C


#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_USE_C


#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_MPI_WINDOW_SIZE 2
#define MBEDTLS_SSL_MAX_CONTENT_LEN 16384 

#include "mbedtls/check_config.h"

#endif