/*
 *  SPDX-License-Identifier: MIT
 *
 *  8086-OS/config.h
 *
 *  Copyright (C) 2026  sosiska565
 *
 *  May be freely distributed as part of 8086-OS.
 */

/* Automatically generated by configure - do not modify */

#define TCC_VERSION "0.9.28rc"

#define CC_NAME CC_gcc
#define GCC_MAJOR 16
#define GCC_MINOR 1

#if !(TCC_TARGET_I386 || TCC_TARGET_X86_64 || TCC_TARGET_ARM || TCC_TARGET_ARM64 || TCC_TARGET_RISCV64 || TCC_TARGET_C67)
#define TCC_TARGET_X86_64 1
#define CONFIG_TCC_LIBPATHS "{B}:/usr/lib64"
#define CONFIG_TCC_CRTPREFIX "/usr/lib64"
#define CONFIG_OS_RELEASE "7.0.9-arch1-1"
#endif

#ifndef CONFIG_TCCDIR
#define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#define CONFIG_TCC_PREDEFS 1
